import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useAccountCenter, useConnectWallet} from '@subwallet_connect/react'
import { ethers } from 'ethers'
import { EIP1193Provider } from '@subwallet_connect/common'
import {useEffect} from "react";

const buttonStyles = {
  borderRadius: '6px',
  background: '#111827',
  border: 'none',
  fontSize: '18px',
  fontWeight: '600',
  cursor: 'pointer',
  color: 'white',
  padding: '14px 12px',
  marginTop: '40px',
  fontFamily: 'inherit'
}

export default function Home(): React.ReactElement {
  const [{ wallet, connecting }, connect, disconnect] = useConnectWallet()
  const changeAccountCenterView = useAccountCenter();


  useEffect(() => {
    changeAccountCenterView({
      expanded : true,
      minimal: false,
      position: "topRight"
    })
  }, []);

  // create an ethers provider
  let ethersProvider

  if (wallet && wallet.type === 'evm') {
    ethersProvider = new ethers.providers.Web3Provider(wallet.provider as EIP1193Provider, 'any')
  }

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans&display=swap" rel="stylesheet" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to this demo of{' '}
            <a href="https://www.subwallet.app/"> SubConnect!</a>
          </h1>

          <button
            style={buttonStyles}
            disabled={connecting}
            onClick={() => (wallet ? disconnect(wallet) : connect())}
          >
            {connecting ? 'Connecting' : wallet ? 'Disconnect' : 'Connect'}
          </button>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          </a>
        </footer>
      </div>
    </>

  )
}
